### ISSUE TITLE
Request for a reviwer

### ISSUE THREAD

**Issue by BouaikIlham** [HSMathebula/movie-booking-app#14]
## In this issue:
- [ ] We create a kanban board for this project [link](https://github.com/HSMathebula/movie-booking-app)
- [ ] In our team there is :+1: 
    - @BouaikIlham 
    - @bamsi 
    - @HSMathebula 
- [ ] 
![Screenshot from 2022-10-05 15-19-19](https://user-images.githubusercontent.com/89751188/194084054-975c76ca-2e83-4f6a-8881-06e3ebbd83f2.png)

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.
